### ISSUE TITLE
Missing parenthese

### ISSUE THREAD

**Issue by polzy** [cglatot/PokeManager#1]
Hi, 
Very good job :) 
I have a problem with the CMD, 

![capture](https://cloud.githubusercontent.com/assets/1337715/17149633/6d83742a-536c-11e6-93d4-aae65385339d.PNG)

You can help me ?

thanks

**Comment by cglatot** [comment]
You need to use Python 2.7. Not 3.x

**Comment by polzy** [comment]
Hum thx .. sorry i try

**Comment by polzy** [comment]
I have Python 2.7.9 with PIP 
After this cmd pip install -r requirements.txt

I have a new problem .. :( 

![capture](https://cloud.githubusercontent.com/assets/1337715/17150673/9cfb28b6-5370-11e6-85fc-73644569b99f.PNG)

**Comment by cglatot** [comment]
Did `pip install -r requirements.txt` complete successfully?

Run `pip install --upgrade -r requirements.txt` and let me see the output

**Comment by polzy** [comment]
Thanks, my log for install and upgrade requirements.txt
[pip.txt](https://github.com/cglatot/PokeManager/files/384553/pip.txt)

**Comment by cglatot** [comment]
I don't want a log. Just do the command I said and show me the print screen. It should not be many lines.

**Comment by Raudaschl** [comment]
@polzy You have to install python 2.7 and pip separately. Installing pip 2.7.9 will not work.

**Comment by polzy** [comment]
Work fine with python 2.7.4 and pip separately, 
Thanks you ! :+1:
