### ISSUE TITLE
Error while starting up

### ISSUE THREAD

**Issue by realjesset** [cglatot/PokeManager#12]
I was starting up and I ran pip requirements, while starting the pokemanger this happened. I don't have 2 Step auth so yeah, don't know why this happened.![capture](https://cloud.githubusercontent.com/assets/16761873/17173947/ee7e8644-540e-11e6-9753-74860f3e5c81.PNG)

**Comment by cglatot** [comment]
Username/Password is probably wrong or mistyped

**Comment by realjesset** [comment]
yup, thnx!
