### ISSUE TITLE
[Feature] Can't display all pokemon result

### ISSUE THREAD

**Issue by elliottfeng** [cglatot/PokeManager#15]
If there are like more than 500 in inventory, can't display every one.
# Solution

Increase the scrollback buffer size. [Windows](http://stackoverflow.com/questions/4692673/how-to-change-screen-buffer-size-in-windows-command-prompt-from-batch-script). [Linux](http://stackoverflow.com/questions/8760346/how-do-i-increase-the-scrollback-buffer-in-a-running-screen-session).

**Comment by cglatot** [comment]
Using which commands?
And "like" 500, or actually 500?
Does it give an error, or does it just go back to the Main Menu?

**Comment by elliottfeng** [comment]
use code 1 to list all
because of too many, can't display all results in window.

**Comment by cglatot** [comment]
Ahhhhh, that will be because of the buffer height of CMD. I'll look into it, but no promises

**Comment by elliottfeng** [comment]
also one suggestion, speed transfer and rename would be better~

**Comment by cglatot** [comment]
Solution to issue: Increase the scrollback buffer size. [Windows](http://stackoverflow.com/questions/4692673/how-to-change-screen-buffer-size-in-windows-command-prompt-from-batch-script). [Linux](http://stackoverflow.com/questions/8760346/how-do-i-increase-the-scrollback-buffer-in-a-running-screen-session).

I won't be adding "speed" transfer and rename. That is just asking for insta bans. Code is available to fork, though.
