### ISSUE TITLE
[Feature] Add an export to CSV option

### ISSUE THREAD

**Issue by adrianocr** [cglatot/PokeManager#16]
The data is basically already formatted correctly anyway. Exporting to a CSV would allow people to get a copy of what they have without having to reload the script every time. Saves on API calls and with a CSV you can use Google Sheets or Excel to do a bunch of stuff with the data.

**Comment by cglatot** [comment]
I will be working on this shortly. Was already considering it, but since you asked so nicely, I will definitely do it :D

**Comment by adrianocr** [comment]
Looking forward to it!

**Comment by cglatot** [comment]
Added in latest commit. Can save to CSV for both View and Counts.
