### ISSUE TITLE
Transfer Pokemon Is Blank after filling criteria

### ISSUE THREAD

**Issue by Raudaschl** [cglatot/PokeManager#2]
Hey there,

Everything is working great, however when I need to filter out Pokemon in the transfer section doesn't return any pokemon.

Any suggestions? Great little piece of software btw! Thanks so much for writing it.

![screen shot 2016-07-26 at 20 24 58](https://cloud.githubusercontent.com/assets/6103284/17152288/0b195626-536f-11e6-84f4-7f335f238b43.png)

**Comment by cglatot** [comment]
You haven't entered the name of any pokemon, that's why.
