### ISSUE TITLE
[Feature] Publish docker images to docker hub 

### ISSUE THREAD

**Issue by gavacho** [cglatot/PokeManager#20]
I see that #18 added a docker file to this repository.  It would be awesome if the docker image were published to docker hub so that I could grab that instead of having to clone the repository and build the image myself.

In the past, I've used travis-ci to publish docker images to docker hub automatically upon certain conditions (e.g. when the master branch is updated, when a new tag is added, etc).

I'd be happy to contribute to this if you'd like.

**Comment by cglatot** [comment]
I'm not familiar with docker or travis-ci. Feel free to clone / fork the project and do it yourself.

**Comment by gavacho** [comment]
Sure, I can definitely open a PR.  Some things, however, will require you to set up before a PR can be opened.

First, you would need to register with docker hub and create a cglatot/PokeManager repository for docker images there.

Second, you would need to enable travis-ci for this github repository.  You can accomplish that at https://travis-ci.org.

Once those are done I can create a PR with a file named `.travis.yml` which will contain instructions for travis to build the docker image on each PR and to then publish it to docker hub when master is updated.

**Comment by cglatot** [comment]
Yeah, I'm not going to do that, sorry. I already have barely enough time as it is . Feel free to create a clone of the project for yourself though.
