### ISSUE TITLE
ANSI color codes don't display properly under Win7

### ISSUE THREAD

**Issue by echo465** [cglatot/PokeManager#22]
Win7/64.  The displays that are supposed to be in color instead are displayed with the ANSI color codes literally.

←[1;37;40m SPEAROW         | 216   | 7   | 6   | 7   | 44  | PECK            | DRILL_PECK ←[0m
←[1;32;40m SPEAROW         | 48    | 11  | 13  | 13  | 82  | PECK            | DRILL_PECK ←[0m

I believe this is related:
http://stackoverflow.com/questions/287871/print-in-terminal-with-colors-using-python

**Comment by cglatot** [comment]
You will have to either run it on a different OS, figure out how to get ANSI color codes working on your machine, or wait until I add the feature to export to CSV.
