### ISSUE TITLE
Can't run on Linux

### ISSUE THREAD

**Issue by sangeet79** [cglatot/PokeManager#23]
Hi!
I tried running PokeManager on Linux, had this as a result:

tokarevi@home-pc:~$ cd /home/tokarevi/PokeManager-master
tokarevi@home-pc:~/PokeManager-master$ ./PokeManager.bat
Traceback (most recent call last):
  File "./pogo/demo.py", line 10, in <module>
    import POGOProtos.Enums.PokemonMove_pb2 as PokemonMove_pb2
  File "/home/tokarevi/PokeManager-master/pogo/POGOProtos/Enums/PokemonMove_pb2.py", line 10, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 180, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: 'module' object has no attribute 'Default'

How can this be corrected?

**Comment by cglatot** [comment]
Did you follow the readme **entirely**? Many people say they have, but in the end they usually haven't.

This includes correct python version, having pip, installed requirements.txt, read the note about 2FA.

**Comment by sangeet79** [comment]
Yep, i'm fairly certain that I followed all the steps and I don't have 2FA.
I had to rework your command line from the *.bat file though, since linux does not understand "\" sign, but i don't think this is the source of my problem.
unfortunatelly the output i provided above does not tell me anything.

**Comment by cglatot** [comment]
What version of Python are you using? Did you try calling the line inside the .bat explicitly from bash, rather than calling the bat file?

**Comment by sangeet79** [comment]
i'm using this:
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2

i tried to call the the bat file from bash, i also tried to call the line from bash.

**bat file result:**
tokarevi@home-pc:~/PokeManager-master$ ./PokeManager.bat
Traceback (most recent call last):
  File "./pogo/demo.py", line 10, in <module>
    import POGOProtos.Enums.PokemonMove_pb2 as PokemonMove_pb2
  File "/home/tokarevi/PokeManager-master/pogo/POGOProtos/Enums/PokemonMove_pb2.py", line 10, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 180, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: 'module' object has no attribute 'Default'

**line result:**
tokarevi@home-pc:~/PokeManager-master$ python "./pogo/demo.py" -a google -u "tokarevi@gmail.com" -p "mypasswordhere" -l "55.754937, 37.633747"
Traceback (most recent call last):
  File "./pogo/demo.py", line 10, in <module>
    import POGOProtos.Enums.PokemonMove_pb2 as PokemonMove_pb2
  File "/home/tokarevi/PokeManager-master/pogo/POGOProtos/Enums/PokemonMove_pb2.py", line 10, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 180, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: 'module' object has no attribute 'Default'

as you can see the result are identical.

**Comment by cglatot** [comment]
Try updating your Python install, then rerun the requirements.txt install.

After that run `pip install --upgrade -r requirements.txt` (in the directory where requirements.txt is)

**Comment by sangeet79** [comment]
ok, i'll try

**Comment by sangeet79** [comment]
Ok, so i solved the problem. You were directing me in the right direction. The default python version for my ubuntu 14.04 is 2.7.6. I downloaded the latest release, which is 2.7.12 installed it from the source. then i used virtual envoriment to set up requirements and ran the program afterwards.
