### ISSUE TITLE
Can't get access token with non-gmail

### ISSUE THREAD

**Issue by ShadowNX01** [cglatot/PokeManager#27]
Hi, i'm playing with a google account that ends with "@tiscali.it", i used this on ingress and started to use it here on PKMN GO as well, but even though the phone app accepts it, something doesn't like it here, either the program or api, so i get:
Access token not generated
Session not created successfully
Do you think there's anything you or i can do to fix this problem?
Thanks in advance

**Comment by cglatot** [comment]
Are you using 2FA?

Did you follow everything in the Readme?

**Comment by ShadowNX01** [comment]
Ok, apparently it was a temporary problem on my side, it seems to be working perfectly now! :)
