### ISSUE TITLE
Access token not generated

### ISSUE THREAD

**Issue by norecha** [cglatot/PokeManager#32]
Cannot login right now. I tried to login with latest api and it worked. It seems like you just copied the python api and modified the demo.py. This tight coupling is very bad and causes problems like these when api needs to be updated, it is very hard to do. Instead you can add the api as a submodule which can be updated on the fly.

**Comment by cglatot** [comment]
Servers might have been down, or you are using 2FA (in which case see the note about that) as it is working fine on all accounts I've tested it with (Google and PTC)

I want to keep this decoupled from the API itself in case any of the changes break my implementation. I manually update it every so often, and so far the API changes have **not** broken my code.
