### ISSUE TITLE
Error opening the .bat

### ISSUE THREAD

**Issue by TheBaconSandwich** [cglatot/PokeManager#33]
Edited the pokemanager.bat correctly, but upon opening it closes after a quarter of a second and I can briefly see 

Starting new HTTPS connection (1): android.clients.google.com
Access token not granted
Session not created successfully

Upon running the .bat as admin it flashes for an even shorter amount of time, and proceeds to do nothing.
No clue what the issue could be, help greatly appreciated.

**Comment by cglatot** [comment]
Are you using Google or PTC to login?

If Google, are you using 2FA? If so, did you read the readme about 2FA?

**Comment by TheBaconSandwich** [comment]
Thanks, everything works now
I didn't have 2 factor authentication enabled but something about setting the app password fixed it.
