### ISSUE TITLE
Error on running the .bat

### ISSUE THREAD

**Issue by Pokem0n2** [cglatot/PokeManager#34]
![capture](https://cloud.githubusercontent.com/assets/20771620/17293683/6520a656-5824-11e6-8d67-750165abb6e0.PNG)
i set everything ok just follow your steps, however, when i ran the .bat file, the window didn't show me a main menu like yours. may u figure out where the trouble is & help me fix this issue? many THANX! :-b

**Comment by cglatot** [comment]
The problem is in your location. Did you correctly set lat/long, or a location recognisable by Google maps?

**Comment by Pokem0n2** [comment]
thanks for answering! here is my lat/long "-33.8934, 151.2062"

**Comment by Pokem0n2** [comment]
btw, this is a set of coordinates in Australia, and Australia got a Pokemon game server.

**Comment by cglatot** [comment]
Copy/paste the line from the bat file here (edit out your username/password, but keep the quotes, etc

**Comment by Pokem0n2** [comment]
`python ".\pogo\demo.py" -a ptc -u "***" -p "***" -l "-33.8934, 151.2062"`

**Comment by cglatot** [comment]
Hmmm, strange - should work from what I can see. What version of Python are you running? And did you install/update the requirements.txt?

**Comment by Pokem0n2** [comment]
yup, i think so. that's extremely weird! i installed PY 2.7.12 and used pip command updating the txt already... :-<

**Comment by cglatot** [comment]
Hmmm I can't see why it isn't working. Try removing the project and redownload from Git?

What OS are you using?

**Comment by Pokem0n2** [comment]
can u pack files which can run properly on ur pc into a .rar and send it to me liangxiao38250@hotmail.com? (P.S remember editing out ur account and password)

**Comment by Pokem0n2** [comment]
running Win 10 Pro now :-)

**Comment by oi-io** [comment]
got same error here with a google account:

```
Creating Google session for xxxxxxx@gmail.com
Starting new HTTPS connection (1): android.clients.google.com
Starting new HTTPS connection (1): android.clients.google.com
Traceback (most recent call last):
  File "demo.py", line 443, in <module>
    session = poko_session.authenticate(args.location)
  File "F:\pokemon\PokeManager\pogo\api.py", line 148, in authenticate
    }[self.provider](locationLookup=locationLookup, noop=noop)
  File "F:\pokemon\PokeManager\pogo\api.py", line 100, in createGoogleSession
    noop=noop
  File "F:\pokemon\PokeManager\pogo\api.py", line 63, in createPogoSession
    location = Location(locationLookup, self.geo_key)
  File "F:\pokemon\PokeManager\pogo\location.py", line 26, in __init__
    self.latitude, self.longitude, self.altitude = self.setLocation(locationLookup)
  File "F:\pokemon\PokeManager\pogo\location.py", line 48, in setLocation
    raise GeneralPogoException('Error in Geo Request')
custom_exceptions.GeneralPogoException: Error in Geo Request
```

tried a few different coordinates too, same coordinates worked on other cl tools like pokemonGo-bot
python2.7.6 on win8
also tried using my own Google map apikey with -g option

**Comment by Pokem0n2** [comment]
finally... lol :-) i've found out where the problem is! it didn't work due to my network connection, authentication at sso.pokemon.com or pgorelease.nianticlabs.com may need normal conn. i just closed my VPN and everything rans well since then. DO appreciate ur works and thanks again!

**Comment by cglatot** [comment]
Thanks for letting me know! Hopefully it can work for others!

**Comment by Pokem0n2** [comment]
@oi-io u may try using a VPN before running the .bat, or just shutting down ur VPN if u are using one, and then rerun the .bat again. hope this would help!

**Comment by oi-io** [comment]
@Pokem0n2, I don't using VPN  and I have been running other Pokemon scripts for a few days, they are connecting the same end point so  I don't think network is the issue. 多谢！
@cglatot I got it around by authenticate without location  `session = poko_session.authenticate()` it's only the transfer function I need to use anyway. Thanks for your input.

**Comment by Pokem0n2** [comment]
@oi-io i run pokeminer, IVTool, PG-DesktopMap etc. properly too, using the same node. nevertheless, only PokeManager need to close the VPN, so why not give it a try dude? :-)

**Comment by oi-io** [comment]
@Pokem0n2 Thanks, but I don't need the location to work.

**Comment by Pokem0n2** [comment]
well, i c... u only need PGO API to achieve the transfer function. good luck!

**Comment by cglatot** [comment]
I removed the need for location in the latest build. It is now optional, and should work without it.

**Comment by Pokem0n2** [comment]
@cglatot that's awesome! do appreciate it!
