### ISSUE TITLE
[Feature] Transfer duplicate pokemon should also use exceptions.config

### ISSUE THREAD

**Issue by Necroskillz** [cglatot/PokeManager#36]
I could pull request if u want, but it's pretty simple change that should be easy enough to do for you.

**Comment by fprovostpoulin** [comment]
I'd like to have this change as well. It would also be nice to have a CP range as well for the dupplicate transfer. Maybe it could be a different exception file for the dupplicates. So I could (lets say) remove All duplicates under X CP and X IV except Pidgey, Caterpie and weedles.  Thanks

**Comment by cglatot** [comment]
Solved with commit #40 by @bartonp

**Comment by bartonp** [comment]
@fprovostpoulin and @cglatot - I have the code for the CP limitation as a global input already. Do you want me to create another pull request or just add it into this one? It's located on this commit if you want to diff it -> https://github.com/bartonp/PokeManager/commit/80dd12f756803e38c8678c14ef55ce8e1cd47135

The separate file would have to be worked out into a different way as you could then have different levels per pokemon.

**Comment by cglatot** [comment]
I've added the CP cutoff - but I do not like the idea of the different files - I don't want this to be getting too complex. There are already so many options to make, I don't see the need for it.

**Comment by fprovostpoulin** [comment]
This is perfect asis ! Maybe adding a question for CP as you do for single
transfer, that would be awesome.

Another thing that could be a nice option is to be able to transfer all the
Non-starred or all of th Starred pokemon. What do you think ?

Thank you very much !

_Félix Provost-Poulin_

Software Engeneer Bacc. and MBA Candidate
_Cellulaire : (514) 463-1978_

2016-08-02 17:54 GMT-04:00 cglatot notifications@github.com:

**Comment by cglatot** [comment]
@fprovostpoulin - I've already added the CP cutoff - look at my last reply.

The transfer duplicates already won't transfer your starred pokemon. Not going to add a separate feature for it

**Comment by fprovostpoulin** [comment]
Okay; I didn't know it wasnt transfering starred pokemon; Maybe you could
just put a note into your user guide :)
Thanks

_Félix Provost-Poulin_

Software Engeneer Bacc. and MBA Candidate
_Cellulaire : (514) 463-1978_

2016-08-03 1:28 GMT-04:00 cglatot notifications@github.com:
