### ISSUE TITLE
Best moves

### ISSUE THREAD

**Issue by fprovostpoulin** [cglatot/PokeManager#41]
It may be nice to have a way to know what are the best moves for a given pokemon and find an heuristic that defines at what IV difference is worthing having the 2 best moves on 1 pokemon vs another one that has lowest moves but has a bit higher IV.

Am I clear enough on the request ?

**Comment by cglatot** [comment]
You can already view the moves of the Pokemon. I won't add anything that shows the "best" moves as they are likely to (and already have) changed.

**Comment by fprovostpoulin** [comment]
Oh that is true; thought you were plugged on a DB that gives the moves dps;
so it could be calculated.

Another (last) question here : Is there a way to run that on my android
mobile ?

Thank you

_Félix Provost-Poulin_

Software Engeneer Bacc. and MBA Candidate
_Cellulaire : (514) 463-1978_

2016-08-03 1:32 GMT-04:00 cglatot notifications@github.com:
