### ISSUE TITLE
Docker container does not user AUTHTYPE environment variable

### ISSUE THREAD

**Issue by Nepoxx** [cglatot/PokeManager#43]
`docker run --rm -it -e "AUTHTYPE=ptc" -e "LOGIN=nepoxx" -e "PASSWORD={myPass}" -e "STARTINGPOINT=X, Y" ryebrye/pokemongo-manager:latest`

results in:

```
Creating Google session for nepoxx
          ^
Starting new HTTPS connection (1): android.clients.google.com
Starting new HTTPS connection (1): android.clients.google.com
Coordinates: X -Y 0.0
Access token not generated
Session not created successfully
```

**Comment by ahmedasmar** [comment]
docker run --rm -it -e "authtype=ptc" -e "LOGIN=nepoxx" -e "PASSWORD={myPass}" -e "STARTINGPOINT=X, Y" ryebrye/pokemongo-manager:latest

variables are case sensitive but the writer of README missed it
