### ISSUE TITLE
Error when choose to transfer pokemon

### ISSUE THREAD

**Issue by mahesoo** [cglatot/PokeManager#44]
Hello I'm using pokemanager on mac osx, the version berfore work flawlessly, but now it's always giving me an error when i'm going to transfer pokemon.
i access this with terminal on os x with command cd ~/Downloads/PokeManager-master/pogo then run python demo.py but when i choose 3 (transfer pokemon) it giving me error messages like this : 

> Enter choice: 3
> Traceback (most recent call last):
>   File "demo.py", line 464, in <module>
>     mainMenu(session)
>   File "demo.py", line 415, in mainMenu
>     elif menuChoice == 3: massRemove(session)
>   File "demo.py", line 35, in massRemove
>     rf = open(os.path.dirname(**file**) + '/../exceptions.config')
> IOError: [Errno 2] No such file or directory: '/../exceptions.config'

Can you help me ? Thanks before :)

**Comment by bartonp** [comment]
Have a look in _~/Downloads/PokeManager-master_ to see if there is a file called _exceptions.config_. If there isn't, create one using `touch exceptions.config`.

**Comment by mahesoo** [comment]
yes the file does exist in the root folder (_~/Downloads/PokeManager-master)_ it seems like the command in demo.py didnt recognize the file, 
maybe because _demo.py_ and _exceptions.config_ not in same folder?, 
_demo.py_ on _~/Downloads/PokeManager-master/pogo_ and the _exceptions.config_ on the root folder (_~/Downloads/PokeManager-master_) i already tried to move the _exceptions.config_ file to pogo folder but it still didnt work.

**Comment by mahesoo** [comment]
Hi bartonp i tried to insert your code to my demo.py the code works but it give message like this 

> No Exceptions file found - '/exceptions.config'

So where i must place the file exceptions.config? 

Thanks for your help :)

**Comment by bartonp** [comment]
I've added some more debugging code for finding why your exceptions file is being pointed there. It will print three lines before saying that no exceptions file has been found.
