### ISSUE TITLE
View Count : Tell how much we have to transfer

### ISSUE THREAD

**Issue by fprovostpoulin** [cglatot/PokeManager#49]
It would be nice to have another column telling us how many we should transfer to optimize our candies. Lets say I have 112 candies and 20 pidgey, I'd like the app to tell me I should transfer :

floor(112/12) = 9 +  4 free
20 piedgey - 9 = 11 pidgey free
if I transfer 12-4 free = 8, i can evolve evolve 1 more, 
So the number of pidgey I really have to transfer is 11-8 = 3
(Also, a column with how many I can evolve Considering transfers could be nice)

**Comment by BeardAnnihilator** [comment]
I made a pull request

**Comment by BeardAnnihilator** [comment]
Related to #56
