### ISSUE TITLE
[Feature] Check for "best" moveset or having any "best" moves

### ISSUE THREAD

**Issue by martinsweitzer** [cglatot/PokeManager#8]
I name my pokemon foo ++ +- -+ --   depending on whether they have the correct moves for their Quick and Main.

I am currently using:  https://pokemon.gameinfo.io/   for which moves are considered the best.

Would be awesome to have this type of functionality in your amazing Manager

**Comment by cglatot** [comment]
Latest commit shows moves.

I likely won't be renaming pokemon based on moves, etc. But this should at least let you view the moves that each has much easier.
