### ISSUE TITLE
[Feature] Allow transfer of duplicates

### ISSUE THREAD

**Issue by SwedishLesbian** [cglatot/PokeManager#9]
Should add an option to allow to transfer duplicates and save highest CP pokemon and / or pokemon that meet cp iv requirements

**Comment by cglatot** [comment]
Stop gap to this feature request could also be an option for "Don't transfer if only Pokemon of type"

**Comment by bartonp** [comment]
See #31, and let me know if you want changes to do the CP/IV matches are per your other removal.

**Comment by cglatot** [comment]
Added in latest commit. Thanks @bartonp
